cluster.name: wazuh-cluster
node.name: wazuh.indexer

network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node

path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer

plugins.security.disabled: true

cluster.routing.allocation.disk.threshold_enabled: false
